---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: flux
  namespace: flux-system
spec:
  interval: 10m0s
  ref:
    tag: v2.0.0-rc.5
  url: https://github.com/fluxcd/flux2
  ignore: |
    # exclude all
    /*
    # include manifest dir
    !/manifests
