---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
components:
  - ../../components/common
resources:
  - ./flaresolverr/ks.yaml
  - ./prowlarr/ks.yaml
  - ./radarr/ks.yaml
  - ./radarruhd/ks.yaml
  - ./radarranime/ks.yaml
  - ./recyclarr/ks.yaml
  - ./sabnzbd/ks.yaml
  - ./sonarr/ks.yaml
  - ./sonarranime/ks.yaml
  - ./sonarruhd/ks.yaml
  - ./tautulli/ks.yaml
  - ./seerr/ks.yaml
  - ./namespace.yaml

