---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: media-namespace
  namespace: flux-system
spec:
  interval: 5m
  path: "./k8s/namespaces/clusters/betty/media"
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: home-cluster
---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: media-bazarr
  namespace: flux-system
spec:
  interval: 5m
  path: "./k8s/namespaces/clusters/betty/media/bazarr"
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: home-cluster
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  dependsOn:
    - name: media-namespace
      namespace: flux-system
  postBuild:
    substitute: {}
    substituteFrom:
      - kind: ConfigMap
        name: cluster-config
      - kind: ConfigMap
        name: global-config
      - kind: Secret
        name: cluster-secrets
---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: media-overseerr
  namespace: flux-system
spec:
  interval: 5m
  path: "./k8s/namespaces/clusters/betty/media/overseerr"
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: home-cluster
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  dependsOn:
    - name: media-namespace
      namespace: flux-system
  postBuild:
    substitute: {}
    substituteFrom:
      - kind: ConfigMap
        name: cluster-config
      - kind: ConfigMap
        name: global-config
      - kind: Secret
        name: cluster-secrets
---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: media-prowlarr
  namespace: flux-system
spec:
  interval: 5m
  path: "./k8s/namespaces/clusters/betty/media/prowlarr"
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: home-cluster
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  dependsOn:
    - name: media-namespace
      namespace: flux-system
  postBuild:
    substitute: {}
    substituteFrom:
      - kind: ConfigMap
        name: cluster-config
      - kind: ConfigMap
        name: global-config
      - kind: Secret
        name: cluster-secrets
---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: media-radarr
  namespace: flux-system
spec:
  interval: 5m
  path: "./k8s/namespaces/clusters/betty/media/radarr"
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: home-cluster
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  dependsOn:
    - name: media-namespace
      namespace: flux-system
  postBuild:
    substitute: {}
    substituteFrom:
      - kind: ConfigMap
        name: cluster-config
      - kind: ConfigMap
        name: global-config
      - kind: Secret
        name: cluster-secrets
---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: media-radarr4k
  namespace: flux-system
spec:
  interval: 5m
  path: "./k8s/namespaces/clusters/betty/media/radarr4k"
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: home-cluster
  dependsOn:
    - name: media-namespace
      namespace: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substitute: {}
    substituteFrom:
      - kind: ConfigMap
        name: cluster-config
      - kind: ConfigMap
        name: global-config
      - kind: Secret
        name: cluster-secrets
---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: media-radarr-anime
  namespace: flux-system
spec:
  interval: 5m
  path: "./k8s/namespaces/clusters/betty/media/radarranime"
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: home-cluster
  dependsOn:
    - name: media-namespace
      namespace: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substitute: {}
    substituteFrom:
      - kind: ConfigMap
        name: cluster-config
      - kind: ConfigMap
        name: global-config
      - kind: Secret
        name: cluster-secrets
---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: media-recyclarr
  namespace: flux-system
spec:
  interval: 5m
  path: "./k8s/namespaces/clusters/betty/media/recyclarr"
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: home-cluster
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  dependsOn:
    - name: media-namespace
      namespace: flux-system
  postBuild:
    substitute: {}
    substituteFrom:
      - kind: ConfigMap
        name: cluster-config
      - kind: ConfigMap
        name: global-config
      - kind: Secret
        name: cluster-secrets
---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: media-sabnzbd
  namespace: flux-system
spec:
  interval: 5m
  path: "./k8s/namespaces/clusters/betty/media/sabnzbd"
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: home-cluster
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  dependsOn:
    - name: media-namespace
      namespace: flux-system
  postBuild:
    substitute: {}
    substituteFrom:
      - kind: ConfigMap
        name: cluster-config
      - kind: ConfigMap
        name: global-config
      - kind: Secret
        name: cluster-secrets
---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: media-sonarr
  namespace: flux-system
spec:
  interval: 5m
  path: "./k8s/namespaces/clusters/betty/media/sonarr"
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: home-cluster
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  dependsOn:
    - name: media-namespace
      namespace: flux-system
  postBuild:
    substitute: {}
    substituteFrom:
      - kind: ConfigMap
        name: cluster-config
      - kind: ConfigMap
        name: global-config
      - kind: Secret
        name: cluster-secrets
---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: media-sonarranime
  namespace: flux-system
spec:
  interval: 5m
  path: "./k8s/namespaces/clusters/betty/media/sonarranime"
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: home-cluster
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  dependsOn:
    - name: media-namespace
      namespace: flux-system
  postBuild:
    substitute: {}
    substituteFrom:
      - kind: ConfigMap
        name: cluster-config
      - kind: ConfigMap
        name: global-config
      - kind: Secret
        name: cluster-secrets
---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: media-tautulli
  namespace: flux-system
spec:
  interval: 5m
  path: "./k8s/namespaces/clusters/betty/media/tautulli"
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: home-cluster
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  dependsOn:
    - name: media-namespace
      namespace: flux-system
  postBuild:
    substitute: {}
    substituteFrom:
      - kind: ConfigMap
        name: cluster-config
      - kind: ConfigMap
        name: global-config
      - kind: Secret
        name: cluster-secrets
---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: media-recyclarr-edge
  namespace: flux-system
spec:
  interval: 5m
  path: "./k8s/namespaces/clusters/betty/media/recyclarr-edge"
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: home-cluster
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  dependsOn:
    - name: media-namespace
      namespace: flux-system
  postBuild:
    substitute: {}
    substituteFrom:
      - kind: ConfigMap
        name: cluster-config
      - kind: ConfigMap
        name: global-config
      - kind: Secret
        name: cluster-secrets
