apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: github-status-token-secret
stringData:
    token: ENC[AES256_GCM,data:1RAMAZ0+9hTZCrYI5z/Y6AxxOVPw1WLYObihXjNCMl4k0m05CcOPhmeYpS6uJoTMeBYNvM2Uqq/2RrZ2ZHgefUoH4MUsMB/sxi96mPLE9ejXcfL7//sod28uzcw7,iv:QeVbdTAO22/bZYecpWMaatU9uYXFyZ4jnzE3N0C+68Y=,tag:qOelDna0grteUqV/A5164Q==,type:str]
sops:
    age:
        - recipient: age15avv4nw90ryfzuste9ww32ttpc4l8m9npqndgq662czy9csum3jskdpexm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzL01QU0pwOXFhL01jSUJr
            MEFEelJHS1U5OFJxemgrVWk2UGNhYTNlK1FZCmtPZFk1ZDVBV1Q2WmxBZVV2bXVW
            QzZwTVJTTmZYdktXRk1uM1BCY283aGMKLS0tIHpaV0NsYXlEL24rUGgyMHpxWkU5
            NW9xWlFZdGxvekpiN3FKMlhva3pRNlEK8cKCfaj/BpA9KsbBuwcJpyDagesel9O9
            EhTLzIqY/nr5NDPWCf0iUHPbjB8QMtA0CQ0C2wInz2nTI4bRXWPgAA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-18T19:14:15Z"
    mac: ENC[AES256_GCM,data:bXj+ciLvXoLT+pk16YrO687hufK4Z+B3d3A9cSBlmw8mSBticJahRZfEbfxgH7kDfgnhQxWoOuljXhoP3rE+jB9iiycVa15KIgtaJ0FEa/MBW0VKkQlfBWXEFghNNSbHnVBduZRyVfblnWFCorfxohiO3PJpFhUktxZdG3nWs/c=,iv:4sa9A0t/7oVHwv/22J17GzCAZM36QccqNRJCm2YjbHw=,tag:SGlRLKg/TrdavRloN3gOxg==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
